name: moneyplan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  firebase_core: ^2.25.4
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_messaging: ^14.7.15
  cloud_firestore: ^4.15.4
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

